[package]
name = "rise_pak_patch"
version = "0.1.0"
authors = ["ricochet"]
edition = "2021"

[dependencies]

[profile.release]
opt-level = 3
debug = 0
overflow-checks = false
lto = "fat"
codegen-units = 1